### ISSUE TITLE
Filer Filesystem assignment fails

### ISSUE THREAD

**Issue by dawnofman** [humphd/browser-shell#5]
replacing the 9P filesystem with Filer with new Object creation '**const options = Object.create(emulatorParams);**' in filesystem.js and assign it to filesystem doesn't work. Did you make any changes in the v86 library JS to make this workaround '**options.filesystem = filerAPI'**;

**Comment by humphd** [comment]
Correct, I had to [hack some things into v86](https://github.com/humphd/v86/tree/filer-9p-lastknowngood).  You can see what I did here:

https://github.com/humphd/v86/compare/f6ae3ea58aee15f2a9be71f2847738367ef31747...humphd:filer-9p-lastknowngood

I haven't looked at this code since I did it, and it was done "to make something work" so there are likely cleaner ways to do it against v86 master now.

**Comment by dawnofman** [comment]
> Correct, I had to [hack some things into v86](https://github.com/humphd/v86/tree/filer-9p-lastknowngood). You can see what I did here:
> 
> [humphd/v86@f6ae3ea...humphd:filer-9p-lastknowngood](https://github.com/humphd/v86/compare/f6ae3ea58aee15f2a9be71f2847738367ef31747...humphd:filer-9p-lastknowngood)
> 
> I haven't looked at this code since I did it, and it was done "to make something work" so there are likely cleaner ways to do it against v86 master now.

Thank you very much! you are a life saver. It all helped me and worked!

**Comment by humphd** [comment]
Awesome, glad you got it!
